
INSERT INTO "WS"."WS_SERVICES" (SERVICE_ID, NAME) VALUES (89, 'ISUR_PROXY');

INSERT INTO "WS"."WS_CONFIG" (NAME_PARAM, SERVICE_ID, VAL_STRING, DESCRIPTION) VALUES ('WSDL', 89, 'http://212.45.30.233:81/IsurTest/Coordinate/V5/Service.svc?singleWsdl', 'Адрес сервиса');

INSERT INTO "WS"."WS_CONFIG" (NAME_PARAM, SERVICE_ID, VAL_STRING, DESCRIPTION) VALUES ('CODE', 89, 'ISUR_PROXY', 'Уникальный код сервиса');

INSERT INTO "WS"."WS_CONFIG" (NAME_PARAM, SERVICE_ID, VAL_STRING, DESCRIPTION) VALUES ('LOGGING_ENABLE', 89, 'true', 'Логирование входящих и исходящих запросов включено');

INSERT INTO "WS"."WS_CONFIG" (NAME_PARAM, SERVICE_ID, VAL_STRING, DESCRIPTION) VALUES ('SIGNATURE_ALIAS', 89, '', 'Наименование сертификата');

INSERT INTO "WS"."WS_CONFIG" (NAME_PARAM, SERVICE_ID, VAL_STRING, DESCRIPTION) VALUES ('SIGNATURE_PASSWORD', 89, '', 'Пароль контейнера с ключом');
