
INSERT INTO "WS"."WS_CONFIG" (NAME_PARAM, SERVICE_ID, VAL_STRING, DESCRIPTION) VALUES ('SIGNATURE_ALIAS', 99, '', 'Наименование сертификата');

INSERT INTO "WS"."WS_CONFIG" (NAME_PARAM, SERVICE_ID, VAL_STRING, DESCRIPTION) VALUES ('SIGNATURE_PASSWORD', 99, '', 'Пароль контейнера с ключом');

INSERT INTO "WS"."WS_CONFIG" (NAME_PARAM, SERVICE_ID, VAL_STRING, DESCRIPTION) VALUES ('LOGGING_ENABLE', 99, 'true', 'Логирование входящих и исходящих запросов включено');

