//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.11.07 at 02:19:58 PM AMT 
//


package ru.rosreestr.client.isur.model.base64;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Governance">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="Governance_Code" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                   &lt;element name="E-mail" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="Agent">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="FIO">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="Surname" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="First" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="Patronymic" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                             &lt;element name="Document">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="Code_Document" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                                       &lt;element name="Series" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                                       &lt;element name="Number" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                                       &lt;element name="Date" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *                                       &lt;element name="IssueOrgan" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                             &lt;element name="E-mail" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="agent_kind" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="declarant_kind" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="signatured" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "governance"
})
public class Declarant {

    @XmlElement(name = "Governance", required = true)
    protected Governance governance;
    @XmlAttribute(name = "declarant_kind")
    protected String declarantKind;
    @XmlAttribute(name = "signatured")
    protected String signatured;

    /**
     * Gets the value of the governance property.
     * 
     * @return
     *     possible object is
     *     {@link Governance }
     *     
     */
    public Governance getGovernance() {
        return governance;
    }

    /**
     * Sets the value of the governance property.
     * 
     * @param value
     *     allowed object is
     *     {@link Governance }
     *     
     */
    public void setGovernance(Governance value) {
        this.governance = value;
    }

    /**
     * Gets the value of the declarantKind property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public String getDeclarantKind() {
        return declarantKind;
    }

    /**
     * Sets the value of the declarantKind property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setDeclarantKind(String value) {
        this.declarantKind = value;
    }

    /**
     * Gets the value of the signatured property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSignatured() {
        return signatured;
    }

    /**
     * Sets the value of the signatured property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSignatured(String value) {
        this.signatured = value;
    }

}
