//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.11.07 at 02:19:58 PM AMT 
//


package ru.rosreestr.client.isur.model.base64;

import javax.xml.bind.annotation.XmlRegistry;
import java.lang.*;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the generated package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: generated
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link RequestGRP }
     * 
     */
    public RequestGRP createRequestGRP() {
        return new RequestGRP();
    }

    /**
     * Create an instance of {@link EDocument }
     * 
     */
    public EDocument createEDocument() {
        return new EDocument();
    }

    /**
     * Create an instance of {@link Request }
     * 
     */
    public Request createRequest() {
        return new Request();
    }

    /**
     * Create an instance of {@link FIRInfo }
     * 
     */
    public FIRInfo createFIRInfo() {
        return new FIRInfo();
    }

    /**
     * Create an instance of {@link RequiredData }
     * 
     */
    public RequiredData createRequiredData() {
        return new RequiredData();
    }

    /**
     * Create an instance of {@link Declarant }
     * 
     */
    public Declarant createDeclarant() {
        return new Declarant();
    }

    /**
     * Create an instance of {@link Payment }
     * 
     */
    public Payment createPayment() {
        return new Payment();
    }

    /**
     * Create an instance of {@link Delivery }
     * 
     */
    public Delivery createDelivery() {
        return new Delivery();
    }

    /**
     * Create an instance of {@link AppliedDocuments }
     * 
     */
    public AppliedDocuments createAppliedDocuments() {
        return new AppliedDocuments();
    }

    /**
     * Create an instance of {@link AppliedDocument }
     * 
     */
    public AppliedDocument createAppliedDocument() {
        return new AppliedDocument();
    }

    /**
     * Create an instance of {@link Quantity }
     * 
     */
    public Quantity createQuantity() {
        return new Quantity();
    }

    /**
     * Create an instance of {@link Original }
     * 
     */
    public Original createOriginal() {
        return new Original();
    }

    /**
     * Create an instance of {@link Governance }
     * 
     */
    public Governance createGovernance() {
        return new Governance();
    }

    /**
     * Create an instance of {@link Agent }
     * 
     */
    public Agent createAgent() {
        return new Agent();
    }

    /**
     * Create an instance of {@link FIO }
     * 
     */
    public FIO createFIO() {
        return new FIO();
    }

    /**
     * Create an instance of {@link Document }
     * 
     */
    public Document createDocument() {
        return new Document();
    }

    /**
     * Create an instance of {@link RequiredDataRealty }
     * 
     */
    public RequiredDataRealty createRequiredDataRealty() {
        return new RequiredDataRealty();
    }

    /**
     * Create an instance of {@link ExtractRealty }
     * 
     */
    public ExtractRealty createExtractRealty() {
        return new ExtractRealty();
    }

    /**
     * Create an instance of {@link Objects }
     * 
     */
    public Objects createObjects() {
        return new Objects();
    }

    /**
     * Create an instance of {@link java.lang.Object }
     * 
     */
    public java.lang.Object createObject() {
        return new java.lang.Object();
    }

    /**
     * Create an instance of {@link ObjKind }
     * 
     */
    public ObjKind createObjKind() {
        return new ObjKind();
    }

    /**
     * Create an instance of {@link CadastralNumbers }
     * 
     */
    public CadastralNumbers createCadastralNumbers() {
        return new CadastralNumbers();
    }

    /**
     * Create an instance of {@link Location }
     * 
     */
    public Location createLocation() {
        return new Location();
    }

    /**
     * Create an instance of {@link Building }
     * 
     */
    public Building createBuilding() {
        return new Building();
    }

}
